import "./style.css";

type Screen = "home" | "game" | "profile" | "collection" | "tournaments" | "settings";
const STORAGE = "legion-prototype-03";
interface SaveData { name:string; level:number; xp:number; games:number; bestScore:number; bestCombo:number; music:boolean; sounds:boolean; vibration:boolean; quality:"low"|"medium"|"high"; }
const defaults:SaveData={name:"Alexandr",level:1,xp:0,games:0,bestScore:0,bestCombo:0,music:true,sounds:true,vibration:true,quality:"high"};
let save:SaveData=load(); let screen:Screen="home"; let game:Game|null=null; let audio:AudioContext|null=null;
function load():SaveData{try{return {...defaults,...JSON.parse(localStorage.getItem(STORAGE)||"{}")}}catch{return {...defaults}}}
function persist(){localStorage.setItem(STORAGE,JSON.stringify(save))}
function xpNeeded(){return save.level*1000}
function addXP(amount:number){save.xp+=amount;while(save.xp>=xpNeeded()){save.xp-=xpNeeded();save.level++}persist()}
function esc(s:string){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!))}
const icons=["✦","◇","◈","⬢","✧","☽"];
const iconNames=["STAR","VOID","PRISM","HEX","COMET","MOON"];
function app(){document.querySelector<HTMLDivElement>("#app")!.innerHTML=`<div class="shell"><div class="ambient a1"></div><div class="ambient a2"></div><header class="topbar"><button class="brand" data-nav="home"><span>LEGION</span><small>TECHNICAL TEST • 0.3</small></button><div class="top-actions"><button class="icon-btn" data-nav="profile">👤</button><button class="icon-btn" data-nav="settings">⚙</button></div></header><main id="screen"></main></div>`;renderScreen()}
function renderScreen(){const el=document.querySelector<HTMLDivElement>("#screen")!;if(screen==="home")el.innerHTML=home();if(screen==="game")el.innerHTML=gameView();if(screen==="profile")el.innerHTML=profile();if(screen==="collection")el.innerHTML=placeholder("КОЛЛЕКЦИЯ","Карточки появятся в следующих версиях Legion.");if(screen==="tournaments")el.innerHTML=placeholder("ТУРНИРЫ","Соревнования и рейтинг пока находятся в разработке.");if(screen==="settings")el.innerHTML=settings();bind()}
function home(){return `<section class="home"><div class="hero"><div class="sigil"><span>L</span></div><div class="eyebrow">DARK ANIME • MATCH PUZZLE</div><h1>LEGION</h1><p>Собери комбинацию. Создай цепь. Разбуди силу.</p></div><div class="menu-grid"><button class="menu-card primary" data-nav="game"><b>ИГРАТЬ</b><span>Три в ряд</span><i>→</i></button><button class="menu-card" data-nav="collection"><b>КОЛЛЕКЦИЯ</b><span>В разработке</span><i>🔒</i></button><button class="menu-card" data-nav="tournaments"><b>ТУРНИРЫ</b><span>В разработке</span><i>🔒</i></button></div><div class="quick-row"><button data-nav="profile">👤 ПРОФИЛЬ</button><button data-nav="settings">⚙ НАСТРОЙКИ</button></div></section>`}
function profile(){const pct=Math.min(100,Math.round(save.xp/xpNeeded()*100));return `<section class="page"><button class="back" data-nav="home">← НАЗАД</button><div class="page-title"><span>PLAYER DATA</span><h2>ПРОФИЛЬ</h2></div><div class="profile-card"><div class="avatar">A</div><div><div class="eyebrow">PLAYER</div><h3>${esc(save.name)}</h3><div class="level">LEVEL ${save.level}</div></div></div><div class="xp"><div><span>XP</span><span>${save.xp} / ${xpNeeded()}</span></div><div class="bar"><i style="width:${pct}%"></i></div></div><div class="stats"><div><small>ИГР</small><strong>${save.games}</strong></div><div><small>ЛУЧШИЙ СЧЁТ</small><strong>${save.bestScore.toLocaleString("ru-RU")}</strong></div><div><small>ЛУЧШЕЕ КОМБО</small><strong>×${save.bestCombo}</strong></div></div></section>`}
function settings(){return `<section class="page"><button class="back" data-nav="home">← НАЗАД</button><div class="page-title"><span>SYSTEM</span><h2>НАСТРОЙКИ</h2></div><div class="settings">${toggle("Музыка","music",save.music)}${toggle("Звуковые эффекты","sounds",save.sounds)}${toggle("Вибрация","vibration",save.vibration)}<div class="setting-row"><div><b>Качество эффектов</b><small>Влияет на частицы</small></div><select id="quality"><option value="low" ${save.quality==="low"?"selected":""}>Низкое</option><option value="medium" ${save.quality==="medium"?"selected":""}>Среднее</option><option value="high" ${save.quality==="high"?"selected":""}>Высокое</option></select></div></div></section>`}
function toggle(label:string,key:keyof SaveData,value:boolean){return `<div class="setting-row"><div><b>${label}</b><small>${value?"Включено":"Выключено"}</small></div><button class="switch ${value?"on":""}" data-setting="${key}"><i></i></button></div>`}
function placeholder(title:string,text:string){return `<section class="page placeholder"><button class="back" data-nav="home">← НАЗАД</button><div class="page-title"><span>COMING SOON</span><h2>${title}</h2></div><div class="lock">🔒</div><p>${text}</p><button class="outline" data-nav="game">ИГРАТЬ В ПРОТОТИП</button></section>`}
function gameView(){return `<section class="game-page"><div class="game-head"><button class="back" data-nav="home">←</button><div><small>SCORE</small><strong id="score">0</strong></div><div><small>COMBO</small><strong id="combo">×0</strong></div><div><small>MOVES</small><strong id="moves">30</strong></div></div><div class="game-status" id="status">СВАЙПАЙ ПО ПОЛЮ</div><div class="combo-meter"><i id="comboMeter"></i></div><div id="board" class="board"></div><div class="game-actions"><button class="outline" id="restart">↻ НОВАЯ ИГРА</button></div></section>`}

class Game{
 size=8; board:number[]=[]; score=0; combo=0; moves=30; locked=false; pointerStart:{x:number,y:number,index:number}|null=null;
 start(){this.board=this.createBoard();this.render();this.attachSwipe()}
 createBoard(){const b:number[]=[];for(let i=0;i<this.size*this.size;i++){let v:number;do{v=Math.floor(Math.random()*icons.length)}while(this.causesMatch(b,i,v));b.push(v)}return b}
 causesMatch(b:number[],i:number,v:number){const x=i%this.size,y=Math.floor(i/this.size);return(x>=2&&b[i-1]===v&&b[i-2]===v)||(y>=2&&b[i-this.size]===v&&b[i-this.size*2]===v)}
 render(){const board=document.querySelector<HTMLDivElement>("#board");if(!board)return;board.innerHTML=this.board.map((v,i)=>`<button class="tile t${v}" data-i="${i}" aria-label="${iconNames[v]}"><span>${icons[v]}</span></button>`).join("");document.querySelector("#score")!.textContent=this.score.toLocaleString("ru-RU");document.querySelector("#combo")!.textContent=`×${this.combo}`;document.querySelector("#moves")!.textContent=String(this.moves);this.updateMeter()}
 attachSwipe(){const board=document.querySelector<HTMLDivElement>("#board");if(!board)return;board.onpointerdown=e=>{if(this.locked||this.moves<=0)return;const tile=(e.target as HTMLElement).closest<HTMLButtonElement>(".tile");if(!tile)return;const index=Number(tile.dataset.i);this.pointerStart={x:e.clientX,y:e.clientY,index};tile.classList.add("touching");board.setPointerCapture(e.pointerId)};board.onpointermove=e=>{if(!this.pointerStart||this.locked)return;const dx=e.clientX-this.pointerStart.x,dy=e.clientY-this.pointerStart.y;const distance=Math.hypot(dx,dy);if(distance>8){const tile=document.querySelector(`.tile[data-i="${this.pointerStart.index}"]`);tile?.classList.add("dragging")}};board.onpointerup=e=>{if(!this.pointerStart)return;const start=this.pointerStart;this.pointerStart=null;document.querySelectorAll(".touching,.dragging").forEach(x=>x.classList.remove("touching","dragging"));if(this.locked||this.moves<=0)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;const threshold=Math.max(18,Math.min(30,board.clientWidth*.045));if(Math.max(Math.abs(dx),Math.abs(dy))<threshold)return;const dir=Math.abs(dx)>Math.abs(dy)?(dx>0?1:-1):(dy>0?this.size:-this.size);const target=start.index+dir;if(target<0||target>=this.board.length)return;if(dir===1&&start.index%this.size===this.size-1)return;if(dir===-1&&start.index%this.size===0)return;this.move(start.index,target)};board.onpointercancel=()=>{this.pointerStart=null;document.querySelectorAll(".touching,.dragging").forEach(x=>x.classList.remove("touching","dragging"))}}
 async move(a:number,b:number){if(this.locked||this.moves<=0)return;this.locked=true;this.swap(a,b);this.animateSwap(a,b);await sleep(150);const matches=this.findMatches();if(!matches.size){this.swap(a,b);this.animateSwap(a,b);this.shake();this.locked=false;return}this.moves--;this.playTone(260,.045,"sine");vibrate(8);await this.resolve(matches);this.locked=false;this.combo=0;if(this.moves<=0)this.finish();else this.render()}
 swap(a:number,b:number){[this.board[a],this.board[b]]=[this.board[b],this.board[a]]}
 animateSwap(a:number,b:number){document.querySelector(`.tile[data-i="${a}"]`)?.classList.add("swap-out");document.querySelector(`.tile[data-i="${b}"]`)?.classList.add("swap-in");setTimeout(()=>document.querySelectorAll(".swap-out,.swap-in").forEach(x=>x.classList.remove("swap-out","swap-in")),180)}
 findMatches(){const set=new Set<number>();for(let y=0;y<this.size;y++){let run=1;for(let x=1;x<=this.size;x++){const cur=x<this.size?this.board[y*this.size+x]:-99,prev=this.board[y*this.size+x-1];if(cur===prev)run++;else{if(run>=3)for(let k=0;k<run;k++)set.add(y*this.size+x-1-k);run=1}}}for(let x=0;x<this.size;x++){let run=1;for(let y=1;y<=this.size;y++){const cur=y<this.size?this.board[y*this.size+x]:-99,prev=this.board[(y-1)*this.size+x];if(cur===prev)run++;else{if(run>=3)for(let k=0;k<run;k++)set.add((y-1-k)*this.size+x);run=1}}}return set}
 async resolve(initial:Set<number>){let chain=0,current=initial;while(current.size){chain++;this.combo=chain;const size=current.size;this.score+=size*125*chain+(size>=4?250:0)+(size>=5?750:0);this.showCombo(chain,size);this.spawnParticles(current,size>=5?"mega":size>=4?"special":"match");current.forEach(i=>document.querySelector(`.tile[data-i="${i}"]`)?.classList.add(size>=5?"burst":"pop"));this.playTone(240+chain*90,size>=5?.16:.08,"triangle");vibrate(size>=5?22:10);await sleep(size>=5?250:190);current.forEach(i=>this.board[i]=-1);this.collapse();this.fill();this.render();await sleep(chain>1?105:80);current=this.findMatches()}if(this.combo>save.bestCombo)save.bestCombo=this.combo;if(this.score>save.bestScore)save.bestScore=this.score;addXP(Math.max(8,Math.floor(this.score/250)));persist()}
 collapse(){for(let x=0;x<this.size;x++){const vals:number[]=[];for(let y=this.size-1;y>=0;y--){const v=this.board[y*this.size+x];if(v!==-1)vals.push(v)}for(let y=this.size-1;y>=0;y--)this.board[y*this.size+x]=vals[this.size-1-y]??-1}}
 fill(){for(let i=0;i<this.board.length;i++)if(this.board[i]===-1)this.board[i]=Math.floor(Math.random()*icons.length)}
 showCombo(chain:number,size:number){const s=document.querySelector("#status");if(s){s.innerHTML=chain>1?`CHAIN <b>×${chain}</b> • ${size} ELEMENTS`:`${size>=5?"LEGION BURST":size===4?"POWER MATCH":"MATCH"} • +${size*125*chain}`;s.classList.remove("pulse");void (s as HTMLElement).offsetWidth;s.classList.add("pulse")}this.updateMeter()}
 updateMeter(){const meter=document.querySelector<HTMLElement>("#comboMeter");if(meter)meter.style.width=`${Math.min(100,this.combo*25)}%`}
 spawnParticles(matches:Set<number>,kind:string){const board=document.querySelector<HTMLDivElement>("#board");if(!board)return;const rect=board.getBoundingClientRect();matches.forEach(i=>{const tile=document.querySelector<HTMLElement>(`.tile[data-i="${i}"]`);if(!tile)return;const tr=tile.getBoundingClientRect();const cx=tr.left-rect.left+tr.width/2,cy=tr.top-rect.top+tr.height/2;const count=save.quality==="low"?2:save.quality==="medium"?4:6;for(let p=0;p<count;p++){const el=document.createElement("i");el.className=`particle ${kind}`;el.style.left=`${cx}px`;el.style.top=`${cy}px`;el.style.setProperty("--dx",`${(Math.random()-.5)*70}px`);el.style.setProperty("--dy",`${(Math.random()-.5)*70}px`);board.appendChild(el);setTimeout(()=>el.remove(),520)}})}
 shake(){const b=document.querySelector("#board");b?.classList.add("shake");setTimeout(()=>b?.classList.remove("shake"),260);this.playTone(110,.05,"sawtooth")}
 finish(){save.games++;persist();const s=document.querySelector("#status");if(s)s.innerHTML=`ИГРА ОКОНЧЕНА • <b>${this.score.toLocaleString("ru-RU")}</b> ОЧКОВ`;this.playTone(180,.15,"sine")}
}
function ensureAudio(){if(!save.sounds)return;try{audio??=new AudioContext();if(audio.state==="suspended")audio.resume()}catch{audio=null}}
function playTone(freq:number,duration:number,type:OscillatorType){ensureAudio();if(!audio||!save.sounds)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.055,audio.currentTime+.012);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration+.02)}
function vibrate(ms:number){if(save.vibration&&navigator.vibrate)navigator.vibrate(ms)}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms))}
function bind(){document.querySelectorAll<HTMLElement>("[data-nav]").forEach(el=>el.onclick=()=>{screen=el.dataset.nav as Screen;if(screen==="game"){renderScreen();game=new Game();game.start();ensureAudio();}else renderScreen()});document.querySelectorAll<HTMLButtonElement>("[data-setting]").forEach(btn=>btn.onclick=()=>{const key=btn.dataset.setting as "music"|"sounds"|"vibration";save[key]=!save[key];persist();renderScreen()});document.querySelector<HTMLSelectElement>("#quality")?.addEventListener("change",e=>{save.quality=(e.target as HTMLSelectElement).value as SaveData["quality"];persist()});document.querySelector("#restart")?.addEventListener("click",()=>{game=new Game();game.start();ensureAudio()})}
app();