import "./style.css";

type Screen="home"|"game"|"profile"|"collection"|"tournaments"|"settings";
type Quality="low"|"medium"|"high";
interface SaveData{name:string;level:number;xp:number;games:number;bestScore:number;bestCombo:number;music:boolean;sounds:boolean;vibration:boolean;quality:Quality}
const STORAGE="legion-prototype-04";const defaults:SaveData={name:"Alexandr",level:1,xp:0,games:0,bestScore:0,bestCombo:0,music:true,sounds:true,vibration:true,quality:"high"};
let save:SaveData=load(),screen:Screen="home",game:Game|null=null,audio:AudioContext|null=null;
const icons=["✦","◇","◈","⬢","✧","☽"],names=["STAR","VOID","PRISM","HEX","COMET","MOON"];
function load():SaveData{try{return{...defaults,...JSON.parse(localStorage.getItem(STORAGE)||"{}")}}catch{return{...defaults}}}function persist(){localStorage.setItem(STORAGE,JSON.stringify(save))}function xpNeeded(){return save.level*1000}function addXP(n:number){save.xp+=n;while(save.xp>=xpNeeded()){save.xp-=xpNeeded();save.level++}persist()}function esc(s:string){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!))}
function app(){document.querySelector<HTMLDivElement>("#app")!.innerHTML=`<div class="shell"><div class="ambient a1"></div><div class="ambient a2"></div><header class="topbar"><button class="brand" data-nav="home"><span>LEGION</span><small>TECHNICAL TEST • 0.4</small></button><div class="top-actions"><button class="icon-btn" data-nav="profile">👤</button><button class="icon-btn" data-nav="settings">⚙</button></div></header><main id="screen"></main></div>`;renderScreen()}
function home(){return`<section class="home"><div class="hero"><div class="sigil"><span>L</span></div><div class="eyebrow">DARK ANIME • MATCH PUZZLE</div><h1>LEGION</h1><p>Собери комбинацию. Создай цепь. Разбуди силу.</p></div><div class="menu-grid"><button class="menu-card primary" data-nav="game"><b>ИГРАТЬ</b><span>Три в ряд • 8 × 8</span><i>→</i></button><button class="menu-card" data-nav="collection"><b>КОЛЛЕКЦИЯ</b><span>В разработке</span><i>🔒</i></button><button class="menu-card" data-nav="tournaments"><b>ТУРНИРЫ</b><span>В разработке</span><i>🔒</i></button></div><div class="quick-row"><button data-nav="profile">👤 ПРОФИЛЬ</button><button data-nav="settings">⚙ НАСТРОЙКИ</button></div></section>`}
function profile(){const pct=Math.min(100,Math.round(save.xp/xpNeeded()*100));return`<section class="page"><button class="back" data-nav="home">← НАЗАД</button><div class="page-title"><span>PLAYER DATA</span><h2>ПРОФИЛЬ</h2></div><div class="profile-card"><div class="avatar">A</div><div><div class="eyebrow">PLAYER</div><h3>${esc(save.name)}</h3><div class="level">LEVEL ${save.level}</div></div></div><div class="xp"><div><span>XP</span><span>${save.xp} / ${xpNeeded()}</span></div><div class="bar"><i style="width:${pct}%"></i></div></div><div class="stats"><div><small>ИГР</small><strong>${save.games}</strong></div><div><small>ЛУЧШИЙ СЧЁТ</small><strong>${save.bestScore.toLocaleString("ru-RU")}</strong></div><div><small>ЛУЧШЕЕ КОМБО</small><strong>×${save.bestCombo}</strong></div></div></section>`}
function settings(){return`<section class="page"><button class="back" data-nav="home">← НАЗАД</button><div class="page-title"><span>SYSTEM</span><h2>НАСТРОЙКИ</h2></div><div class="settings">${toggle("Музыка","music",save.music)}${toggle("Звуковые эффекты","sounds",save.sounds)}${toggle("Вибрация","vibration",save.vibration)}<div class="setting-row"><div><b>Качество эффектов</b><small>Влияет на частицы</small></div><select id="quality"><option value="low" ${save.quality==="low"?"selected":""}>Низкое</option><option value="medium" ${save.quality==="medium"?"selected":""}>Среднее</option><option value="high" ${save.quality==="high"?"selected":""}>Высокое</option></select></div></div></section>`}
function toggle(label:string,key:string,value:boolean){return`<div class="setting-row"><div><b>${label}</b><small>${value?"Включено":"Выключено"}</small></div><button class="switch ${value?"on":""}" data-setting="${key}"><i></i></button></div>`}function placeholder(title:string,text:string){return`<section class="page placeholder"><button class="back" data-nav="home">← НАЗАД</button><div class="page-title"><span>COMING SOON</span><h2>${title}</h2></div><div class="lock">🔒</div><p>${text}</p><button class="outline" data-nav="game">ИГРАТЬ В ПРОТОТИП</button></section>`}function gameView(){return`<section class="game-page"><div class="game-head"><button class="back" data-nav="home">←</button><div><small>SCORE</small><strong id="score">0</strong></div><div><small>COMBO</small><strong id="combo">×0</strong></div><div><small>MOVES</small><strong id="moves">30</strong></div></div><div class="game-status" id="status">СВАЙПАЙ ПО ПОЛЮ</div><div class="combo-meter"><i id="comboMeter"></i></div><div id="board" class="board"></div><div class="game-actions"><button class="outline" id="restart">↻ НОВАЯ ИГРА</button></div></section>`}
function renderScreen(){const el=document.querySelector<HTMLDivElement>("#screen")!;if(game)game.destroy();game=null;el.innerHTML=screen==="home"?home():screen==="profile"?profile():screen==="collection"?placeholder("КОЛЛЕКЦИЯ","Карточки появятся в следующих версиях Legion."):screen==="tournaments"?placeholder("ТУРНИРЫ","Соревнования и рейтинг пока находятся в разработке."):screen==="settings"?settings():gameView();bind();if(screen==="game"){game=new Game();game.start()}}
class Game{size=8;board:number[]=[];score=0;combo=0;moves=30;locked=false;startPoint:{x:number;y:number;index:number}|null=null;pointerId:number|null=null;
start(){this.board=this.createBoard();this.render();this.attachInput()}destroy(){const b=document.querySelector<HTMLDivElement>("#board");if(b)b.onpointerdown=b.onpointermove=b.onpointerup=b.onpointercancel=b.onlostpointercapture=null;this.clearPointer()}restart(){this.destroy();this.score=0;this.combo=0;this.moves=30;this.locked=false;this.board=this.createBoard();this.render();this.attachInput();setStatus("НОВАЯ ИГРА • УДАЧИ")}
createBoard(){const b:number[]=[];for(let i=0;i<this.size*this.size;i++){let v:number;do{v=Math.floor(Math.random()*icons.length)}while(this.causesMatch(b,i,v));b.push(v)}return b}causesMatch(b:number[],i:number,v:number){const x=i%this.size,y=Math.floor(i/this.size);return x>1&&b[i-1]===v&&b[i-2]===v||y>1&&b[i-this.size]===v&&b[i-this.size*2]===v}
render(){const board=document.querySelector<HTMLDivElement>("#board");if(!board)return;board.innerHTML=this.board.map((v,i)=>`<button class="tile t${v}" data-i="${i}" aria-label="${names[v]}"><span>${icons[v]}</span></button>`).join("");setText("score",this.score.toLocaleString("ru-RU"));setText("combo",`×${this.combo}`);setText("moves",String(this.moves));this.updateMeter()}
attachInput(){const board=document.querySelector<HTMLDivElement>("#board");if(!board)return;board.onpointerdown=e=>{if(this.locked||this.moves<=0)return;ensureAudio();const tile=(e.target as HTMLElement).closest<HTMLButtonElement>(".tile");if(!tile)return;this.pointerId=e.pointerId;this.startPoint={x:e.clientX,y:e.clientY,index:Number(tile.dataset.i)};tile.classList.add("touching");try{board.setPointerCapture(e.pointerId)}catch{}};board.onpointermove=e=>{if(!this.startPoint||this.pointerId!==e.pointerId||this.locked)return;const dx=e.clientX-this.startPoint.x,dy=e.clientY-this.startPoint.y;const distance=Math.hypot(dx,dy);if(distance<=5)return;const horizontal=Math.abs(dx)>=Math.abs(dy);const axis=horizontal?dx:dy;const sign=axis>=0?1:-1;const dir=horizontal?sign:sign*this.size;const target=this.startPoint.index+dir;const valid=target>=0&&target<this.board.length&&!(horizontal&&((sign>0&&this.startPoint.index%this.size===this.size-1)||(sign<0&&this.startPoint.index%this.size===0)));const step=board.clientWidth/this.size;const travel=Math.min(step*.96,Math.max(-step*.96,axis));const tx=horizontal?travel:0,ty=horizontal?0:travel;const selected=document.querySelector<HTMLElement>(`.tile[data-i="${this.startPoint.index}"]`);if(selected){selected.classList.add("dragging");selected.style.transform=`translate3d(${tx}px,${ty}px,0) scale(.96)`}if(valid){const neighbor=document.querySelector<HTMLElement>(`.tile[data-i="${target}"]`);if(neighbor){neighbor.classList.add("drag-target");const neighborTravel=travel-sign*step;neighbor.style.transform=horizontal?`translate3d(${neighborTravel}px,0,0)`: `translate3d(0,${neighborTravel}px,0)`}}board.classList.add("tracking")};board.onpointerup=e=>{if(!this.startPoint||this.pointerId!==e.pointerId)return;const s=this.startPoint,dx=e.clientX-s.x,dy=e.clientY-s.y;const threshold=Math.max(20,board.clientWidth*.065);this.clearPointer();if(Math.max(Math.abs(dx),Math.abs(dy))<threshold)return;const dir=Math.abs(dx)>=Math.abs(dy)?(dx>0?1:-1):(dy>0?this.size:-this.size),target=s.index+dir;if(target<0||target>=this.board.length||(dir===1&&s.index%this.size===7)||(dir===-1&&s.index%this.size===0))return;this.move(s.index,target)};board.onpointercancel=()=>this.clearPointer();board.onlostpointercapture=()=>{if(this.startPoint)this.clearPointer()}}
clearPointer(){this.startPoint=null;this.pointerId=null;document.querySelectorAll<HTMLElement>(".touching,.dragging,.drag-target").forEach(x=>{x.classList.remove("touching","dragging","drag-target");x.style.transform=""});document.querySelector("#board")?.classList.remove("tracking")}
async move(a:number,b:number){if(this.locked||this.moves<=0)return;this.locked=true;this.swap(a,b);this.render();await sleep(190);const matches=this.findMatches();if(!matches.size){this.swap(a,b);this.render();this.shake();setStatus("НЕТ КОМБИНАЦИИ");playTone(120,.07,"sawtooth");this.locked=false;return}this.moves--;this.combo=0;playTone(270,.06,"sine");vibrate(7);await this.resolve(matches);this.locked=false;if(this.moves<=0)this.finish();else{this.combo=0;this.render()}}
swap(a:number,b:number){[this.board[a],this.board[b]]=[this.board[b],this.board[a]]}
findMatches(){const set=new Set<number>();for(let y=0;y<8;y++){let start=0;for(let x=1;x<=8;x++){const same=x<8&&this.board[y*8+start]===this.board[y*8+x];if(!same){if(x-start>=3)for(let k=start;k<x;k++)set.add(y*8+k);start=x}}}for(let x=0;x<8;x++){let start=0;for(let y=1;y<=8;y++){const same=y<8&&this.board[start*8+x]===this.board[y*8+x];if(!same){if(y-start>=3)for(let k=start;k<y;k++)set.add(k*8+x);start=y}}}return set}
async resolve(current:Set<number>){let chain=0;while(current.size){chain++;this.combo=chain;const n=current.size,mult=1+Math.min(4,(chain-1)*.5),bonus=n>=5?700:n===4?300:0;this.score+=Math.round(n*120*mult+bonus);setStatus(chain>1?`ЦЕПЬ ×${chain} • ${n} ЭЛЕМЕНТОВ`:n>=5?"LEGION BURST":n===4?"POWER MATCH":"MATCH");this.spawnParticles(current,n>=5?"mega":n===4?"special":"match");current.forEach(i=>document.querySelector(`.tile[data-i="${i}"]`)?.classList.add(n>=5?"burst":"pop"));playTone(260+chain*85,n>=5?.16:.09,n>=5?"triangle":"sine");vibrate(n>=5?22:9);await sleep(n>=5?300:220);current.forEach(i=>this.board[i]=-1);this.collapse();this.fill();this.render();await sleep(125);current=this.findMatches()}if(this.combo>save.bestCombo)save.bestCombo=this.combo;if(this.score>save.bestScore)save.bestScore=this.score;addXP(Math.max(10,Math.floor(this.score/300)));persist()}
collapse(){for(let x=0;x<8;x++){const vals:number[]=[];for(let y=7;y>=0;y--){const v=this.board[y*8+x];if(v!==-1)vals.push(v)}for(let y=7;y>=0;y--)this.board[y*8+x]=vals[7-y]??-1}}fill(){for(let i=0;i<64;i++)if(this.board[i]===-1)this.board[i]=Math.floor(Math.random()*icons.length)}
updateMeter(){const m=document.querySelector<HTMLElement>("#comboMeter");if(m)m.style.width=`${Math.min(100,this.combo*25)}%`}spawnParticles(set:Set<number>,kind:string){const board=document.querySelector<HTMLDivElement>("#board");if(!board||save.quality==="low"&&kind!=="mega")return;const rect=board.getBoundingClientRect(),count=save.quality==="high"?(kind==="mega"?9:5):3;set.forEach(i=>{const t=document.querySelector<HTMLElement>(`.tile[data-i="${i}"]`);if(!t)return;const r=t.getBoundingClientRect();for(let p=0;p<count;p++){const q=document.createElement("i");q.className=`particle ${kind}`;q.style.left=`${r.left-rect.left+r.width/2}px`;q.style.top=`${r.top-rect.top+r.height/2}px`;q.style.setProperty("--dx",`${(Math.random()-.5)*90}px`);q.style.setProperty("--dy",`${(Math.random()-.5)*90}px`);board.appendChild(q);setTimeout(()=>q.remove(),600)}})}shake(){document.querySelector("#board")?.classList.add("shake");setTimeout(()=>document.querySelector("#board")?.classList.remove("shake"),280)}finish(){save.games++;persist();setStatus(`ИГРА ОКОНЧЕНА • ${this.score.toLocaleString("ru-RU")} ОЧКОВ`);playTone(180,.15,"sine")}}
function setText(id:string,v:string){const e=document.getElementById(id);if(e)e.textContent=v}function setStatus(v:string){const e=document.getElementById("status");if(e){e.innerHTML=v;e.classList.remove("pulse");void e.offsetWidth;e.classList.add("pulse")}}function ensureAudio(){if(!save.sounds)return;try{audio??=new AudioContext();if(audio.state==="suspended")void audio.resume()}catch{audio=null}}function playTone(freq:number,duration:number,type:OscillatorType){ensureAudio();if(!audio||!save.sounds)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.055,audio.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration+.02)}function vibrate(ms:number){if(save.vibration&&navigator.vibrate)navigator.vibrate(ms)}function sleep(ms:number){return new Promise<void>(r=>setTimeout(r,ms))}
function bind(){document.querySelectorAll<HTMLElement>("[data-nav]").forEach(el=>el.onclick=()=>{screen=el.dataset.nav as Screen;renderScreen();if(screen==="game")ensureAudio()});document.querySelectorAll<HTMLButtonElement>("[data-setting]").forEach(btn=>btn.onclick=()=>{const key=btn.dataset.setting as "music"|"sounds"|"vibration";save[key]=!save[key];persist();renderScreen()});document.querySelector<HTMLSelectElement>("#quality")?.addEventListener("change",e=>{save.quality=(e.target as HTMLSelectElement).value as Quality;persist();renderScreen()});document.querySelector("#restart")?.addEventListener("click",()=>{game?.restart();ensureAudio()})}
app();
